#include "../hdr/14041_FS_Superblock.h"

#ifndef GLOBALVARS_H
#define GLOBALVARS_H

#define BLOCKSIZE_B 4096
#define BLOCKCHUNKSIZE_b 32
#define BLOCKCHUNKSIZE_B 4
#define BLOCKSIZE_KB (BLOCKSIZE_B / 1024)

#define CHUNKS_PER_BLOCK (BLOCKSIZE_B / BLOCKCHUNKSIZE_B)

#define INODESIZE_B 256
#define INODE_DDL 14

#define DIRMAPSIZE_B 1024
#define DIRMAPSIZE_KB (DIRMAPSIZE_B / 1024)

#define INODE_PER_BLOCK (BLOCKSIZE_B / INODESIZE_B)
#define BITMAP_PER_BLOCK (BLOCKSIZE_B * 8)
#define DIRMAP_PER_BLOCK (BLOCKSIZE_B / DIRECTMAPSIZE_B)

fssuperblock_t SUPERBLOCK;

#endif